-- Bulk-seed the job_sources catalog with ATS boards discovered from the public
-- SimplifyJobs new-grad/internship READMEs (scripts/mine-ats-boards.ts). Each row
-- is one company's public board; the ingest worker already knows how to fetch all
-- five platforms (greenhouse/lever/ashby/smartrecruiters/workable) — these rows
-- just tell it WHERE. Curl-verified: a sample across every platform returned live
-- postings. `on conflict do nothing` (against job_sources_dedup_idx) skips the few
-- already hand-seeded (e.g. figma) and makes re-applying safe.
insert into public.job_sources (kind, source, token, display_name) values
  ('ats_board', 'ashby', '8vc', '8VC'),
  ('ats_board', 'ashby', 'AfterQuery', 'AfterQuery'),
  ('ats_board', 'ashby', 'apex-technology-inc', 'Apex'),
  ('ats_board', 'ashby', 'applied', 'Applied Intuition'),
  ('ats_board', 'ashby', 'astera', 'Astera'),
  ('ats_board', 'ashby', 'Authorium', 'Authorium'),
  ('ats_board', 'ashby', 'base-power', 'Base Power'),
  ('ats_board', 'ashby', 'binance.us', 'Binance'),
  ('ats_board', 'ashby', 'brainco', 'Brain Co.'),
  ('ats_board', 'ashby', 'capy', 'Capy'),
  ('ats_board', 'ashby', 'centerfield', 'Centerfield'),
  ('ats_board', 'ashby', 'clera', 'Clera'),
  ('ats_board', 'ashby', 'collective', 'Collective'),
  ('ats_board', 'ashby', 'confido', 'Confido'),
  ('ats_board', 'ashby', 'cylake-inc', 'Cylake'),
  ('ats_board', 'ashby', 'deliveroo', 'Deliveroo'),
  ('ats_board', 'ashby', 'ellipsislabs', 'Ellipsis Labs'),
  ('ats_board', 'ashby', 'espa', 'Espa AI'),
  ('ats_board', 'ashby', 'flagright.com', 'Flagright'),
  ('ats_board', 'ashby', 'flashpoint.io', 'Flashpoint'),
  ('ats_board', 'ashby', 'foxglove', 'Foxglove'),
  ('ats_board', 'ashby', 'gen-digital', 'Gen Digital'),
  ('ats_board', 'ashby', 'gigaml', 'Giga AI'),
  ('ats_board', 'ashby', 'greatquestion', 'Great Question'),
  ('ats_board', 'ashby', 'hadrian-automation', 'Hadrian'),
  ('ats_board', 'ashby', 'heron-power', 'Heron Power'),
  ('ats_board', 'ashby', 'hiverge', 'Hiverge'),
  ('ats_board', 'ashby', 'icon', 'Icon'),
  ('ats_board', 'ashby', 'julius', 'Julius AI'),
  ('ats_board', 'ashby', 'kos.ai', 'kos.ai'),
  ('ats_board', 'ashby', 'lambda', 'Lambda'),
  ('ats_board', 'ashby', 'Lightfield', 'Lightfield'),
  ('ats_board', 'ashby', 'liquid', 'Liquid'),
  ('ats_board', 'ashby', 'maxima', 'Maxima'),
  ('ats_board', 'ashby', 'melotech', 'Melotech'),
  ('ats_board', 'ashby', 'meshy', 'Meshy'),
  ('ats_board', 'ashby', 'mirage', 'Mirage'),
  ('ats_board', 'ashby', 'n1', 'N1'),
  ('ats_board', 'ashby', 'niural', 'Niural'),
  ('ats_board', 'ashby', 'northslope-technologies', 'Northslope Technologies'),
  ('ats_board', 'ashby', 'NorthwoodSpace', 'Northwood Space'),
  ('ats_board', 'ashby', 'notion', 'Notion'),
  ('ats_board', 'ashby', 'NPX', 'Nuclear Promise X'),
  ('ats_board', 'ashby', 'orb', 'Orb'),
  ('ats_board', 'ashby', 'outmarket', 'Outmarket AI'),
  ('ats_board', 'ashby', 'parallel', 'Parallel Web Systems'),
  ('ats_board', 'ashby', 'people-culture-talent', 'People Culture Talent'),
  ('ats_board', 'ashby', 'periodic-labs', 'Periodic Labs'),
  ('ats_board', 'ashby', 'PointOne', 'PointOne'),
  ('ats_board', 'ashby', 'Preference-Model', 'Preference Model'),
  ('ats_board', 'ashby', 'realmalliance', 'Realm'),
  ('ats_board', 'ashby', 'remarcable-inc', 'Remarcable'),
  ('ats_board', 'ashby', 'sentilink', 'SentiLink'),
  ('ats_board', 'ashby', 'snowflake', 'Snowflake'),
  ('ats_board', 'ashby', 'solink', 'Solink'),
  ('ats_board', 'ashby', 'super.com', 'Super'),
  ('ats_board', 'ashby', 'teamworks', 'Teamworks'),
  ('ats_board', 'ashby', 'titan-msp', 'Titan'),
  ('ats_board', 'ashby', 'tracebit', 'Tracebit'),
  ('ats_board', 'ashby', 'uncountable', 'Uncountable'),
  ('ats_board', 'ashby', 'wealth-com', 'Wealth.com'),
  ('ats_board', 'greenhouse', '60decibelsinc', '60decibelsinc'),
  ('ats_board', 'greenhouse', 'affirm', 'Affirm'),
  ('ats_board', 'greenhouse', 'altaresourcetechnologiesinc', 'Alta Resource Technologies'),
  ('ats_board', 'greenhouse', 'amarok', 'AMAROK Security'),
  ('ats_board', 'greenhouse', 'andurilindustries', 'Anduril'),
  ('ats_board', 'greenhouse', 'applytotruebuilt', 'TrueBuilt'),
  ('ats_board', 'greenhouse', 'aquaticcapitalmanagement', 'Aquatic Capital Management'),
  ('ats_board', 'greenhouse', 'arine', 'Arine'),
  ('ats_board', 'greenhouse', 'artefactus', 'Artefact'),
  ('ats_board', 'greenhouse', 'asteraearlycareer2026', 'Astera Labs'),
  ('ats_board', 'greenhouse', 'axon', 'Axon'),
  ('ats_board', 'greenhouse', 'babelstreet', 'Babel Street'),
  ('ats_board', 'greenhouse', 'billiontoone', 'BillionToOne'),
  ('ats_board', 'greenhouse', 'botauto', 'Bot Auto'),
  ('ats_board', 'greenhouse', 'brightai', 'BrightAI'),
  ('ats_board', 'greenhouse', 'bugcrowd', 'Bugcrowd'),
  ('ats_board', 'greenhouse', 'clarityinnovates', 'Clarity Innovations'),
  ('ats_board', 'greenhouse', 'clinicalarchitecture', 'Clinical Architecture'),
  ('ats_board', 'greenhouse', 'cresta', 'Cresta'),
  ('ats_board', 'greenhouse', 'd3', 'D3'),
  ('ats_board', 'greenhouse', 'docugami', 'Docugami'),
  ('ats_board', 'greenhouse', 'dv01', 'dv01'),
  ('ats_board', 'greenhouse', 'epickids', 'Epic Kids'),
  ('ats_board', 'greenhouse', 'eulerity', 'Eulerity'),
  ('ats_board', 'greenhouse', 'evolver', 'Evolver'),
  ('ats_board', 'greenhouse', 'figma', 'Figma'),
  ('ats_board', 'greenhouse', 'freedomconsulting', 'Freedom Technology Solutions Group'),
  ('ats_board', 'greenhouse', 'fschumacherco', 'F. Schumacher & Co.'),
  ('ats_board', 'greenhouse', 'genevatrading', 'Geneva Trading'),
  ('ats_board', 'greenhouse', 'genscript', 'GenScript'),
  ('ats_board', 'greenhouse', 'iherb', 'iHerb'),
  ('ats_board', 'greenhouse', 'instead', 'Instead'),
  ('ats_board', 'greenhouse', 'ispottv', 'iSpot.tv'),
  ('ats_board', 'greenhouse', 'jobsatphamily', 'Phamily'),
  ('ats_board', 'greenhouse', 'kensingtontours', 'Kensington'),
  ('ats_board', 'greenhouse', 'later', 'Later'),
  ('ats_board', 'greenhouse', 'lilasciences', 'Lila Sciences'),
  ('ats_board', 'greenhouse', 'lucidmotors', 'Lucid Motors'),
  ('ats_board', 'greenhouse', 'mthreerecruitingportal', 'mthree'),
  ('ats_board', 'greenhouse', 'neuralink', 'Neuralink'),
  ('ats_board', 'greenhouse', 'newsbreak', 'NewsBreak'),
  ('ats_board', 'greenhouse', 'offerup', 'OfferUp'),
  ('ats_board', 'greenhouse', 'perpay', 'Perpay'),
  ('ats_board', 'greenhouse', 'pingidentity', 'Ping Identity'),
  ('ats_board', 'greenhouse', 'plscareers', 'PLS'),
  ('ats_board', 'greenhouse', 'podium81', 'Podium'),
  ('ats_board', 'greenhouse', 'pointc', 'Point C'),
  ('ats_board', 'greenhouse', 'queracomputinginc', 'QuEra Computing'),
  ('ats_board', 'greenhouse', 'scaleai', 'Scale AI'),
  ('ats_board', 'greenhouse', 'scoutai', 'Scout AI'),
  ('ats_board', 'greenhouse', 'sezzle', 'Sezzle'),
  ('ats_board', 'greenhouse', 'shein', 'SHEIN'),
  ('ats_board', 'greenhouse', 'sigmacomputing', 'Sigma Computing'),
  ('ats_board', 'greenhouse', 'silananotechnologies', 'Sila Nanotechnologies'),
  ('ats_board', 'greenhouse', 'sonyinteractiveentertainmentglobal', 'Sony Interactive Entertainment'),
  ('ats_board', 'greenhouse', 'spacex', 'SpaceX'),
  ('ats_board', 'greenhouse', 'technergetics', 'Technergetics'),
  ('ats_board', 'greenhouse', 'tenstorrentuniversity', 'Tenstorrent'),
  ('ats_board', 'greenhouse', 'thenuclearcompany', 'The Nuclear Company'),
  ('ats_board', 'greenhouse', 'torcrobotics', 'Torc Robotics'),
  ('ats_board', 'greenhouse', 'tpcengineeringholdingsllc', 'Trexon'),
  ('ats_board', 'greenhouse', 'transmarketgroup', 'TransMarket Group'),
  ('ats_board', 'greenhouse', 'tribalscale', 'TribalScale'),
  ('ats_board', 'greenhouse', 'trueanomalyinc', 'True Anomaly'),
  ('ats_board', 'greenhouse', 'twitch', 'Twitch'),
  ('ats_board', 'greenhouse', 'uareai', 'Uare.ai'),
  ('ats_board', 'greenhouse', 'wonderschool', 'Wonderschool'),
  ('ats_board', 'greenhouse', 'xpengmotors', 'XPENG Motors'),
  ('ats_board', 'lever', 'aledade', 'Aledade'),
  ('ats_board', 'lever', 'datalabusa', 'Datalab USA'),
  ('ats_board', 'lever', 'diversified-automation', 'Diversified Automation'),
  ('ats_board', 'lever', 'evrealty-us', 'EV Realty'),
  ('ats_board', 'lever', 'field-ai', 'Field AI'),
  ('ats_board', 'lever', 'fluxergy-2', 'Fluxergy'),
  ('ats_board', 'lever', 'genbio', 'GenBio AI'),
  ('ats_board', 'lever', 'ifm-us', 'Institute of Foundation Models'),
  ('ats_board', 'lever', 'ivo', 'Ivo'),
  ('ats_board', 'lever', 'latitudeinc', 'Latitude'),
  ('ats_board', 'lever', 'palantir', 'Palantir'),
  ('ats_board', 'lever', 'pingwind', 'PingWind'),
  ('ats_board', 'lever', 'plus-2', 'PlusAI'),
  ('ats_board', 'lever', 'reply', 'Reply'),
  ('ats_board', 'lever', 'tri', 'Toyota Research Institute'),
  ('ats_board', 'lever', 'webfx', 'WebFX'),
  ('ats_board', 'lever', 'whoop', 'Whoop'),
  ('ats_board', 'lever', 'wyetechllc', 'Wyetech'),
  ('ats_board', 'smartrecruiters', 'AGTechnologies1', 'AG Technologies'),
  ('ats_board', 'smartrecruiters', 'BoschGroup', 'Bosch Home Comfort'),
  ('ats_board', 'smartrecruiters', 'Continental', 'Continental'),
  ('ats_board', 'smartrecruiters', 'Eurofins', 'Eurofins'),
  ('ats_board', 'smartrecruiters', 'GDMSI', 'General Dynamics UK'),
  ('ats_board', 'smartrecruiters', 'InsilicoLogix', 'Insilico Logix'),
  ('ats_board', 'smartrecruiters', 'KrgTechnologyInc', 'KRG Technologies'),
  ('ats_board', 'smartrecruiters', 'NorthStarStaffingSolutions1', 'North Star Staffing Solutions'),
  ('ats_board', 'smartrecruiters', 'Sandisk', 'Sandisk'),
  ('ats_board', 'smartrecruiters', 'ServiceNow', 'ServiceNow'),
  ('ats_board', 'smartrecruiters', 'SQexpetsLLC', 'Software Quality Experts'),
  ('ats_board', 'smartrecruiters', 'TheWonderfulCompany', 'The Wonderful Company'),
  ('ats_board', 'workable', 'eluvio', 'Eluvio'),
  ('ats_board', 'workable', 'pony-dot-ai', 'pony.ai'),
  ('ats_board', 'workable', 'quadric-dot-i-o-inc', 'Quadric'),
  ('ats_board', 'workable', 'rokt', 'Rokt')
on conflict do nothing;
